version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=tjddl234
      - DB_NAME=business_db
  db:
    image: mysql:8
    container_name: business-backend
    environment:
      MYSQL_ROOT_PASSWORD: tjddl234
      MYSQL_DATABASE: business_db
    ports:
      - "3307:3306"
